spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example
    username: app
    password: strong_password

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect