spring:
  config:
    import: aws-parameterstore:/cloud-app/prod/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/example
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    aws:
      s3:
        bucket: park-sung-bucket
      region:
        static: ap-northeast-2
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

cloudfront:
  domain: cloudfrontdomain
  keyPairId: keypairid
  privateKeyPem: privateKeyPem